name: News Monitor

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests openai

      - name: Run news monitor
        id: monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Checking OpenAI API key..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi
          python .github/scripts/monitor_news.py

      - name: Commit and push if changed
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/incidents.json
          
          echo "=== News Monitor Summary ==="
          echo "Time: $(date)"
          
          if git diff --staged --quiet; then
            echo "Status: No new incidents found"
            echo "summary=No new incidents found" >> $GITHUB_OUTPUT
            exit 0
          else
            # Count new incidents
            NEW_INCIDENTS=$(git diff --staged data/incidents.json | grep -c '"date":')
            echo "Status: Found $NEW_INCIDENTS new incidents"
            echo "New incidents:"
            git diff --staged data/incidents.json | grep -A 2 '"description":'
            
            git commit -m "Update incidents from news monitor
            
            Found $NEW_INCIDENTS new incidents from automated monitoring.
            Run ID: $GITHUB_RUN_ID"
            
            git push
            echo "summary=Added $NEW_INCIDENTS new incidents" >> $GITHUB_OUTPUT
          fi
          echo "=========================="

      - name: Create summary
        run: |
          echo "### News Monitor Results" >> $GITHUB_STEP_SUMMARY
          echo "Run at: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "Result: ${{ steps.commit.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ steps.commit.outputs.summary }}" != "No new incidents found" ]]; then
            echo "Changes have been committed and pushed to the repository." >> $GITHUB_STEP_SUMMARY
          fi

  deploy:
    needs: monitor
    if: success() && github.event_name != 'schedule'
    uses: ./.github/workflows/hugo-deploy.yml 